### ISSUE TITLE
Look into why it's crashing recently

### ISSUE THREAD

**Issue by obla** [ozfortress/booker-bot#7] opened 2017-06-22 09:17 UTC

**Comment by BenjaminSchaaf** [comment] 2017-06-22 12:37
Has it only "crashed" once recently, or is this more common?

**Comment by obla** [comment] 2017-06-22 12:47
Once since your fix

**Comment by BenjaminSchaaf** [comment] 2017-06-22 12:49
Alright, since this hasn't been reproduced I'll close this issue for now.

**Closed as completed by BenjaminSchaaf** 2017-06-22 12:49 UTC
